name: SCEssentials
version: 0.1.0
main: com.alexogden.core.SCEssentials
description: SkyCraft Modular Plugin
author: Alex Ogden
website: https://github.com/AlexOgden
api-version: '1.20'

commands:
  sce:
    description: SCEssentials general commands
    usage: /sce
    permission: sce.admin
  eclean:
    description: Manually Trigger an entity cleanup
    usage: /eclean
    permission: sce.admin
  jukebox:
    description: Enable of Disable InfiniJukebox
    usage: /jukebox <enable | disable>
    permission: sce.admin
  server:
    description: Open or Close the Server
    usage: /server <close | open>
    permission: sce.admin